version: '3'

services:

  db:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_PASSWORD=beerstore
      - POSTGRES_USER=beerstore
      - POSTGRES_DB=beerstore
    ports:
      - 5432:5432

  app:
    build:
      context: "."
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/beerstore
    ports:
      - 8080:8080
    depends_on:
      - db
